services:
  twingate_connector:
    container_name: twingate-hlab
    restart: always
    image: twingate/connector:1.79.0
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_ANALYTICS=v2
      - TWINGATE_LOG_LEVEL=3
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
