services:
  portainer:
    image: portainer/portainer-ce:2.33.1
    container_name: portainer-hlab
    ports:
      - 9443:9443
    volumes:
      - ${PRTNR_DIR}/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      portainer_network:

networks:
  portainer_network:
    external: true
